# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Grant Elliott's Ideas
author: Grant Elliott
email: grant@grantelliott.ca
description: >- # this means to ignore newlines until "baseurl:"
    Collections of stuff and things as I remember to post them.
    Probably about projects I'm working on, both electronic and software.
    Watch this site to see where it goes!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://grantelliott.ca" # the base hostname & protocol for your site, e.g. http://example.com

github_username:  grelliott
linkedin_username: grantrelliott
mastodon:
  - username: grantelliott
    instance: mstdn.ca

# stop drafts from being published in feed
show_drafts: false
show_excerpts: true

defaults:
  -
    scope:
      path: ""
    values:
      author: Grant Elliott

# Build settings
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    block:
      line-numbers: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap

header_pages:
  - about.md
  - experiments.md

include:
  - .well-known/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - TODO
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache
  - .sass-cache
  - .gitignore
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
